#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import re
import warnings
from sys import argv, stderr, stdin, stdout

warnings.simplefilter(action='ignore', category=FutureWarning)

pattern = argv[1]

try:
    regex = re.compile(pattern)
except re.error as err:
    stderr.write(f'Invalid regex: {err}')
    exit(1)

for line in stdin:
    if regex.search(line):
        stdout.write(line)
