#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from sys import argv, stdin, stdout

for line in stdin:
    if argv[1] in line:
        stdout.write(line)
