#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import json
from sys import stderr, stdin, stdout

try:
    _dict = json.load(stdin)
except json.JSONDecodeError as err:
    stderr.write(f'Invalid JSON: {err}')
    exit(1)

json.dump(
    _dict,
    stdout,
    indent='  ',
    ensure_ascii=False
)
