#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from hashlib import md5
from sys import stdin, stdout

stdout.write(md5(stdin.read().encode()).hexdigest())
