#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from hashlib import sha256
from sys import stdin, stdout

stdout.write(sha256(stdin.read().encode()).hexdigest())
