#!/usr/bin/env python3

# Hey, this is the script of your new tool.
# It's easy. Read string from stdin, return result to stdout.

# You can use your favourite language,
# not only Python. Just replace comand in first line
# (https://en.wikipedia.org/wiki/Shebang_(Unix))

# IMPORTANT: trailing newline isn't ignored, so you shouldn't
# print it if you don't really want it to be in result string.

from sys import stdin, stdout

# Read from stdin...
input_string = stdin.read()

# ...process string...
output_string = '...'

# And write it to stdout
stdout.write(output_string)
